events {
    worker_connections 1024;
}
http {
    upstream poker_hubs {
        server hub-vegas:5001;
        server hub-macau:5001;
        server hub-monaco:5001;
    }
    server{
        listen 80;
        location / {
            proxy_pass http://poker_hubs;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}